# This file is used to create a secret that will be used to pull images from the private registry
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secrets
data:
  .dockerconfigjson: >-
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJjM1JrTFRBek15MDFPVHBuYkdSMExXNWhlVk16WjFaRlZrWlZlWEF4UTFKMFZFWmEiCiAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson