---
stages:
  - terraform
  - kubernetes
  - helm

yc-terraform:
  stage: kubernetes
  trigger:
    include:
      - local: 'terraform/.gitlab-ci.yml'
    strategy: depend
  # rules:
  #   - changes:
  #     - frontend/**/*

yc-kubernetes:
  stage: kubernetes
  needs:
    - job: yc-terraform
      artifacts: true
  trigger:
    include:
      - local: 'kubernetes/.gitlab-ci.yml'
    strategy: depend
  # rules:
  #   - changes:
  #     - frontend/**/*

# helm:
#   stage: helm
#   trigger:
#     include:
#       - local: 'momo-store-chart/.gitlab-ci.yml'
#     strategy: depend
