global:
  image:
    registry: gitlab.praktikum-services.ru:5050
    repository: std-033-59/sausage-store
  appname: sausage-store
  environment: dev
  repository: https://nexus.praktikum-services.tech/repository/sausage-store-helm-mikhail-kurenkov-033-new/