image:
  name: hashicorp/terraform:1.5.7
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

cache:
  paths:
    - .terraform

variables:
  YC_SERVICE_ACCOUNT_KEY_FILE: /tmp/yc-sa-key.json

before_script:
  - cd terraform
  - |
    cat <<EOF >> ~/.terraformrc
    provider_installation {
      network_mirror {
        url = "https://terraform-mirror.yandexcloud.net/"
        include = ["registry.terraform.io/*/*"]
      }
      direct {
        exclude = ["registry.terraform.io/*/*"]
      }
    }
    EOF
  - terraform init
  - echo $YC_KEY > /tmp/yc-sa-key.json

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script: 
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
    - ls -la
  artifacts:
    paths:
      - terraform/planfile

apply:
  stage: apply
  script:
    - terraform apply -auto-approve "planfile"
<<<<<<< HEAD
  when: manual
=======
    - export CLUSTER_ID=$(terraform output -raw cluster_id)
    - apk update
    - apk add bash curl
    - export PATH="$PATH:/root/yandex-cloud/bin"
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - yc config set cloud-id $YC_CLOUD_ID
    - yc config set folder-id $YC_FOLDER_ID
    - yc config set service-account-key /tmp/yc-sa-key.json
    - export YC_TOKEN=$(yc iam create-token)
    - yc managed-kubernetes cluster get-credentials $CLUSTER_ID --external --force
    - cp /root/.kube/config ./kubeconfig
  when: manual
  artifacts:
    paths:
      - terraform/kubeconfig
    expire_in: 8h
>>>>>>> 0b04307 (add helm charts)
