image:
  name: hashicorp/terraform:1.5.7
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

cache:
  paths:
    - .terraform

variables:
  YC_SERVICE_ACCOUNT_KEY_FILE: /tmp/yc-sa-key.json

before_script:
  - cd terraform
  - |
    cat <<EOF >> ~/.terraformrc
    provider_installation {
      network_mirror {
        url = "https://terraform-mirror.yandexcloud.net/"
        include = ["registry.terraform.io/*/*"]
      }
      direct {
        exclude = ["registry.terraform.io/*/*"]
      }
    }
    EOF
  - terraform init
  - echo $YC_KEY > /tmp/yc-sa-key.json

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script: 
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
    - ls -la
  artifacts:
    paths:
      - terraform/planfile

apply:
  stage: apply
  script:
    - terraform apply -auto-approve "planfile"
  when: manual