# This file is used to create a secret that will be used to pull images from the private registry
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secrets
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllYSm5iMk5rT21kc1pIUXRZUzFWVEc5TFJuazFjRXM0WDBFeVpubzBTM1k9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson