# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault
#   labels:
#     app: vault
# data:
#   vault_token: aHZzLlpsaG1vc2dkSExvd1pYQTNtd0tkcXpWRwo=
# type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: backend-secrets
data:
  .dockerconfigjson: >-
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJjM1JrTFRBek15MDFPVHBuYkdSMExXNWhlVk16WjFaRlZrWlZlWEF4UTFKMFZFWmEiCiAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson