---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  nginx.conf: |
    events {
    }
    http {
      server {
          listen 8080;
          server_name localhost;

          root /usr/share/nginx/html;
        index index.html index.htm index.nginx-debian.html;
          
          location /auth {
              proxy_pass http://backend-service:8081;
          }
          location /products {
              proxy_pass http://backend-service:8081/products;
          }
          location /categories {
              proxy_pass http://backend-service:8081/categories;
          }
            location /catalog/products {
              proxy_pass http://backend-service:8081/products;
          }
          location /catalog/categories {
              proxy_pass http://backend-service:8081/categories;
          }
        location / {
          try_files $uri $uri/ =404;
        }
      }
    }