---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-033-59/momo-store/momo-frontend:latest
          resources:
            requests:
              cpu: "0.1"
            limits:
              cpu: "0.1"    
          ports:
          - containerPort: 8080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dockersock
              mountPath: /tmp/docker.sock
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      imagePullSecrets:
        - name: frontend-secrets
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: nginx-conf
          configMap:
            name: frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf 