---
kind: Secret
apiVersion: v1
metadata:
  name: frontend-secrets
data:
  .dockerconfigjson: >-
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJjM1JrTFRBek15MDFPVHBuYkdSMExXNWhlVk16WjFaRlZrWlZlWEF4UTFKMFZFWmEiCiAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson