# The registry and repository values are defined in the global section of the values.yaml file.
# The variables are used in the deployment.yaml file to define the image field in the containers section.
image:
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 0.1
  limits:
    cpu: 0.1
strategy:
  type: Recreate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 1
replicas: 2
revisionHistoryLimit: 12
envServicePort: 8080
mongodb:
  uri: mongodb://mongodb:27017/sausage-store #dummy value
affinity:
  weight: 50
  key: os
  operator: In
  values: linux
antiaffinity:
  weight: 50
# The variables are used in the hpa.yaml file.
hpa:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    type: Resource
  resource: 
    name: cpu
    target:
      type: Utilization  
      averageUtilization: 75